services:
  apache-php83:
    build:
      context: .docker/apache-php83
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - DB_HOST=mariadb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    volumes:
      - ./src:/var/www/html
      - ./data:/data
      - ./.docker/apache-php83/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/apache-php83/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - 3306
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb